---
- name: Deploy Docker Compose stack
  hosts: localhost
  remote_user: ankita
  become: true
  vars_files:
    - vault.txt

  tasks:
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Pull Backend Image
      docker_image:
        name: ankitaagrawal12/prosepetals-backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: ankitaagrawal12/prosepetals-frontend
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/SPE_Major_Project/docker-compose.yml
        dest: ./docker-compose.yml

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: ./
