---
- name: Deploy Docker Compose stack
  hosts: localhost
  remote_user: ankita
  become: true

  tasks:
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Pull Backend Image
      docker_image:
        name: ankitaagrawal12/prosepetals-backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: ankitaagrawal12/prosepetals-frontend
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/SPE_majorproject/docker-compose.yml
        dest: /home/ankita/docker-compose.yml
        owner: ankita
        group: ankita
        mode: '0644'

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: /home/ankita

    - name: Clean up dangling Docker images on localhost
      shell: |
        docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi
      ignore_errors: yes

    - name: Clean up dangling Docker images on remote server
      shell: |
        docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi
      delegate_to: remoteserver
      ignore_errors: yes
