---
- name: Deploy Docker Compose stack
  hosts: localhost
  remote_user: ankita
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"
    backend_image: ""
    frontend_image: ""

  tasks:
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Pull Backend Image
      docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/SPE_Major_Project/docker-compose.yml
        dest: ./docker-compose.yml

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: ./
      environment:
        BACKEND_IMAGE: "{{ backend_image }}"
        FRONTEND_IMAGE: "{{ frontend_image }}"
